name: Bug report
description: Create a report to help us improve
title: "[BUG]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
      - label: I have searched the existing issues
        required: true
  - type: textarea
    attributes:
      label: Current Behavior
      description: A concise description of what you're experiencing.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: dropdown
    id: driver
    attributes:
      label: What driver are you using to see the problem?
      multiple: false
      options:
        - local-storage
        - s3
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - v1.0.0
        - v1.0.1
        - v1.0.2
        - v1.0.3
        - v1.0.4
        - v1.0.5
    validations:
      required: true
  - type: textarea
    id: to-reproduce
    attributes:
      label: Steps To Reproduce
      description: "Steps to reproduce the behavior:"
      placeholder: |
        1. How did the configuration look like
        2. What type of call was made
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context:"
      description: Add any other context about the problem here.