name: unit-and-integration-tests

on:
  push:
    branches:
      - "**"

jobs:
  unit-and-integration-tests:
    name: unit and integration tests
    runs-on: ubuntu-latest
    steps:
      - name: run go 1.17
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Checkout code
        uses: actions/checkout@v2

      - name: execute tests
        shell: bash
        run: make test
